pay_bubble_external_hostname = "ccpay-bubble.aat.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.aat.platform.hmcts.net"
pay_bubble_external_cert_name = "star-aat"
pay_bubble_external_cert_vault_uri = "https://infra-vault-nonprod.vault.azure.net/"
managed_identity_object_id = "b4dba399-85f4-4aa7-b118-1907e2ebe70e"
