pay_bubble_external_hostname = "ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_cert_name = "wildcard-ithc-platform-hmcts-net"
pay_bubble_external_cert_vault_uri = "https://infra-vault-qa.vault.azure.net/"
managed_identity_object_id = "b4dba399-85f4-4aa7-b118-1907e2ebe70e"
