pay_bubble_external_hostname = "ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_cert_name = "wildcard-ithc-platform-hmcts-net"
pay_bubble_external_cert_vault_uri = "https://infra-vault-qa.vault.azure.net/"
managed_identity_object_id = "f4fb1ee8-961f-4e65-a448-be296bd89bdf"
