pay_bubble_external_hostname = "ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.ithc.platform.hmcts.net"
pay_bubble_external_cert_name = "wildcard-ithc-platform-hmcts-net"
pay_bubble_external_cert_vault_uri = "https://infra-vault-qa.vault.azure.net/"
managed_identity_object_id = "1dd234ea-2e74-4dd9-99fe-c1c08d72466b"
