pay_bubble_external_hostname = "ccpay-bubble.perftest.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.perftest.platform.hmcts.net"
pay_bubble_external_cert_name = "star-perftest"
pay_bubble_external_cert_vault_uri = "https://infra-vault-nonprod.vault.azure.net/"
managed_identity_object_id = "49af827b-2ef8-4de7-8236-f88b18ad76f9"