pay_bubble_external_hostname = "ccpay-bubble.sandbox.platform.hmcts.net"
pay_bubble_external_hostname_www = "www.ccpay-bubble.sandbox.platform.hmcts.net"
pay_bubble_external_cert_name = "STAR-sandbox-platform-hmcts-net"
pay_bubble_external_cert_vault_uri = "https://infra-vault-sandbox.vault.azure.net/"
managed_identity_object_id = "fdf9a66e-3555-4f08-9404-3256307b4b11"
